apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 182bd2867ae9042f
    app.humanitec.io/env-type: production
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: spring-kafka
    app.humanitec.io/env-id: production
    app.humanitec.io/org-id: humaniteclab
  name: resource-80bd716f1b056145bc6710e922565c6aa0417801
spec:
  configMapName: resource-configmap-80bd716f1b056145bc6710e922565c6aa0417801
  dependsOn:
  - resource-5949cc79ce5c72f28441610af7ba2bc659132fac
  - resource-bf30bcba90ae561fb552931727740d42aef0e50c
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies:
      - ${resources["postgres.default#modules.spring-kafka-score.externals.db"].guresid}
      id: spring-kafka-score
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: spring-kafka-score
        containers:
          spring-kafka:
            id: spring-kafka
            image: clecio/spring-kafka:latest
            variables:
              DB_HOST: $\{externals.db.host}
              DB_NAME: $\{externals.db.name}resources
              DB_PASSWORD: $\{externals.db.password}
              DB_PORT: $\{externals.db.port}
              DB_USERNAME: $\{externals.db.username}
        deployment:
          minReadySeconds: 5
          replicas: 1
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
        service:
          ports:
            http:
              container_port: 8080
              protocol: TCP
              service_port: 8080
  driverType: humanitec/template
  guresid: 80bd716f1b056145bc6710e922565c6aa0417801
  id: modules.spring-kafka-score
  secretName: resource-secret-80bd716f1b056145bc6710e922565c6aa0417801
  type: workload
  workloadPatchName: resource-patch-80bd716f1b056145bc6710e922565c6aa0417801
status: {}
