apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: hum-rp-redis-ex-redis
    app.humanitec.io/definition-version-id: 28aae733-9ee5-404a-ac81-dfeb9b865bd2
    app.humanitec.io/deployment: 1826f9fe882114f2
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: fb06f9b1e83bc242
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-45deb4c783b10bc323907e5c352c912a63ef7e13
spec:
  configMapName: resource-configmap-45deb4c783b10bc323907e5c352c912a63ef7e13
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      values:
        resId: ${context.res.id}
        templates:
          cookie: |
            port: {{ .init.port }}
            name: {{ .init.name }}
          init: |-
            {{- if .cookie }}
            port: {{ .cookie.port }}
            name: {{ .cookie.name }}
            {{- else }}
            port: 6379
            # Deployment names shouldn't be > 47 https://pauldally.medium.com/why-you-try-to-keep-your-deployment-names-to-47-characters-or-less-1f93a848d34c
            {{ if regexMatch "modules\\.[a-z0-9-]+\\.externals" .driver.values.resId }}
            name: redis-{{ index (splitList "." .driver.values.resId) 1 | substr 0 20 }}-{{ index (splitList "." .driver.values.resId) 3 | substr 0 20 }}
            {{- else }}
            name: redis-{{ index (splitList "." .driver.values.resId) 1 | substr 0 40 }}
            {{- end }}
            {{- end }}
          manifests: |-
            deployment.yaml:
              location: namespace
              data:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: {{ .init.name }}
                spec:
                  selector:
                    matchLabels:
                      app: {{ .init.name }}
                  template:
                    metadata:
                      labels:
                        app: {{ .init.name }}
                    spec:
                      automountServiceAccountToken: false
                      securityContext:
                        fsGroup: 65532
                        runAsGroup: 65532
                        runAsNonRoot: true
                        runAsUser: 65532
                        seccompProfile:
                          type: RuntimeDefault
                      containers:
                      - name: {{ .init.name }}
                        securityContext:
                          allowPrivilegeEscalation: false
                          capabilities:
                            drop:
                              - ALL
                          privileged: false
                          readOnlyRootFilesystem: true
                        image: redis:7-alpine
                        ports:
                        - name: tcp-redis
                          containerPort: 6379
                        volumeMounts:
                        - mountPath: /data
                          name: redis-data
                      volumes:
                      - name: redis-data
                        emptyDir: {}
            service.yaml:
              location: namespace
              data:
                apiVersion: v1
                kind: Service
                metadata:
                  name: {{ .init.name }}
                spec:
                  type: ClusterIP
                  selector:
                    app: {{ .init.name }}
                  ports:
                  - name: tcp-redis
                    port: {{ .init.port }}
                    targetPort: tcp-redis
          outputs: |-
            host: {{ .init.name }}
            port: {{ .init.port }}
          secrets: |-
            username: ""
            password: ""
  driverType: humanitec/template
  guresid: 45deb4c783b10bc323907e5c352c912a63ef7e13
  id: modules.flask-api-score.externals.my-redis
  secretName: resource-secret-45deb4c783b10bc323907e5c352c912a63ef7e13
  type: redis
  workloadPatchName: resource-patch-45deb4c783b10bc323907e5c352c912a63ef7e13
status: {}
