apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 182bd7b57ba5164f
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: spring-kafka
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-60ed5fe3191fc3fa6473edfd413a5d2a2fb55c36
spec:
  configMapName: resource-configmap-60ed5fe3191fc3fa6473edfd413a5d2a2fb55c36
  dependsOn:
  - resource-7a3a76d6d5e573822db4fc2bdb00757fcfeb5244
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies:
      - ${resources["postgres.default#modules.spring-kafka-score.externals.db"].guresid}
      id: spring-kafka-score
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: spring-kafka-score
        containers:
          spring-kafka:
            id: spring-kafka
            image: clecio/spring-kafka:latest
            variables:
              DB_HOST: $\{externals.db.host}
              DB_NAME: $\{externals.db.name}resources
              DB_PASSWORD: $\{externals.db.password}
              DB_PORT: $\{externals.db.port}
              DB_USERNAME: $\{externals.db.username}
        deployment:
          minReadySeconds: 5
          replicas: 1
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
        service:
          ports:
            http:
              container_port: 8080
              protocol: TCP
              service_port: 8080
  driverType: humanitec/template
  guresid: 60ed5fe3191fc3fa6473edfd413a5d2a2fb55c36
  id: modules.spring-kafka-score
  secretName: resource-secret-60ed5fe3191fc3fa6473edfd413a5d2a2fb55c36
  type: workload
  workloadPatchName: resource-patch-60ed5fe3191fc3fa6473edfd413a5d2a2fb55c36
status: {}
