apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/account: gcp2
    app.humanitec.io/definition-id: postgres-cloud
    app.humanitec.io/definition-version-id: ef43b368-c1da-460a-9be5-fc0a756bff29
    app.humanitec.io/deployment: 182a300d8e121f3d
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: 8c831f437669f921
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: spring-kafka
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-6071c4dc2d94a148c4a6c57ce79224b3200961b4
spec:
  configMapName: resource-configmap-6071c4dc2d94a148c4a6c57ce79224b3200961b4
  dependsOn: []
  driver: https://drivers.humanitec.io/postgres-cloudsql
  driverInputs:
    driver:
      secrets:
      - remoteRef:
          key: orgs--humaniteclab--resources--defs--postgres-cloud--driver_secrets--dbcredentials--username
          version: "1"
        secretKey: dbcredentials.username
        secretStoreName: my-gsm
      - remoteRef:
          key: orgs--humaniteclab--resources--defs--postgres-cloud--driver_secrets--dbcredentials--password
          version: "1"
        secretKey: dbcredentials.password
        secretStoreName: my-gsm
      values:
        instance: humanitec-1:us-central1:postgres
        name: postgres-cloud
  driverType: humanitec/postgres-cloudsql
  guresid: 6071c4dc2d94a148c4a6c57ce79224b3200961b4
  id: modules.spring-kafka-score.externals.postgres
  secretName: resource-secret-6071c4dc2d94a148c4a6c57ce79224b3200961b4
  type: postgres
  workloadPatchName: resource-patch-6071c4dc2d94a148c4a6c57ce79224b3200961b4
status: {}
