apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-route
    app.humanitec.io/definition-version-id: 1266f49f-dbc8-4998-bfe1-b2d0f2c31fb8
    app.humanitec.io/deployment: 182a2f97d3aabcfd
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: e1ccf5e735011a72
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: spring-kafka
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-f729b99848972009b643187529c9ba9e4c68f1f2
spec:
  configMapName: resource-configmap-f729b99848972009b643187529c9ba9e4c68f1f2
  dependsOn:
  - resource-b922605b279d4fab063112cfd1781b95c0445f09
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          init: |
            serviceName: {{ if regexMatch `modules\.[a-z0-9-]+\.externals` `modules.spring-kafka-score.externals.route` -}}
              {{- index (splitList "." `modules.spring-kafka-score.externals.route`) 1 | quote -}}
            {{- else -}}
              {{- fail `A route must be added as a private resource dependency. ID: modules.spring-kafka-score.externals.route` -}}
            {{- end }}
          outputs: |
            host: {{ .resource.host | quote }}
            path: {{ .resource.path | quote }}
            port: {{ .resource.port }}
            service: {{ .init.serviceName | quote }}
    resource:
      host: ${resources["dns.default#modules.spring-kafka-score.externals.dns"].outputs.host}
      path: /
      port: 8080
  driverType: humanitec/template
  guresid: f729b99848972009b643187529c9ba9e4c68f1f2
  id: modules.spring-kafka-score.externals.route
  secretName: resource-secret-f729b99848972009b643187529c9ba9e4c68f1f2
  type: route
  workloadPatchName: resource-patch-f729b99848972009b643187529c9ba9e4c68f1f2
status: {}
