apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: redis-tf
    app.humanitec.io/definition-version-id: 84225461-3cc6-4f9e-91b6-bf26ca7a3661
    app.humanitec.io/deployment: 182825670f1e5451
    app.humanitec.io/env-type: production
    app.humanitec.io/matching-criteria-id: a3cd5d191de31812
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api
    app.humanitec.io/env-id: production
    app.humanitec.io/org-id: humaniteclab
  name: resource-8dc870414bd6e7d6ac78e45bf463465e647c95f7
spec:
  configMapName: resource-configmap-8dc870414bd6e7d6ac78e45bf463465e647c95f7
  dependsOn: []
  driver: https://drivers.humanitec.io/terraform
  driverInputs:
    driver:
      values: {}
  driverType: humanitec/terraform
  guresid: 8dc870414bd6e7d6ac78e45bf463465e647c95f7
  id: modules.flask-api-score.externals.my-redis
  secretName: resource-secret-8dc870414bd6e7d6ac78e45bf463465e647c95f7
  type: redis
  workloadPatchName: resource-patch-8dc870414bd6e7d6ac78e45bf463465e647c95f7
status: {}
