apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 182823b3bf276439
    app.humanitec.io/env-type: production
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api
    app.humanitec.io/env-id: production
    app.humanitec.io/org-id: humaniteclab
  name: resource-456f71615e82c1e727e8ebacc5e2322914eb1a7d
spec:
  configMapName: resource-configmap-456f71615e82c1e727e8ebacc5e2322914eb1a7d
  dependsOn:
  - resource-8bc709ed2e4a790c58a913aa5147024c42fa84c6
  - resource-8dc870414bd6e7d6ac78e45bf463465e647c95f7
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies:
      - ${resources["mongodb.default#modules.flask-api-score.externals.my-mongodb"].guresid}
      - ${resources["redis.default#modules.flask-api-score.externals.my-redis"].guresid}
      id: flask-api-score
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: flask-api-score
        containers:
          flask-api:
            id: flask-api
            image: clecio/flask-api:latest
            variables:
              MONGO_URI: $\{externals.my-mongodb.connection}mydb?authSource=admin
              MONGODB_CONNECTION_STRING: $\{externals.my-mongodb.connection}
              REDIS_CONNECTION_STRING: $\{externals.my-redis.host}:$\{externals.my-redis.port},user=$\{externals.my-redis.username},password=$\{externals.my-redis.password}
        deployment:
          minReadySeconds: 5
          replicas: 1
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
        service:
          ports:
            http:
              container_port: 5000
              protocol: TCP
              service_port: 5000
  driverType: humanitec/template
  guresid: 456f71615e82c1e727e8ebacc5e2322914eb1a7d
  id: modules.flask-api-score
  secretName: resource-secret-456f71615e82c1e727e8ebacc5e2322914eb1a7d
  type: workload
  workloadPatchName: resource-patch-456f71615e82c1e727e8ebacc5e2322914eb1a7d
status: {}
