apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 1825edeca54f4778
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api-test
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
spec:
  configMapName: resource-configmap-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  dependsOn:
  - resource-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
  - resource-e8bf0472ccecba849feeff1156acef99070e3b91
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies:
      - ${resources["mongodb.default#modules.my-sample-workload.externals.my-mongodb"].guresid}
      - ${resources["redis.default#modules.my-sample-workload.externals.my-redis"].guresid}
      id: my-sample-workload
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: my-sample-workload
        containers:
          my-sample-container:
            id: my-sample-container
            image: nginx:latest
            variables:
              MONGODB_CONNECTION_STRING: $\{externals.my-mongodb.connection}
              REDIS_CONNECTION_STRING: $\{externals.my-redis.host}:$\{externals.my-redis.port},user=$\{externals.my-redis.username},password=$\{externals.my-redis.password}
  driverType: humanitec/template
  guresid: ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  id: modules.my-sample-workload
  secretName: resource-secret-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  type: workload
  workloadPatchName: resource-patch-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
status: {}
