apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 1825659aa36399f5
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api-test
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
spec:
  configMapName: resource-configmap-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies: []
      id: my-sample-workload
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: my-sample-workload
        containers:
          my-sample-container:
            id: my-sample-container
            image: nginx:latest
  driverType: humanitec/template
  guresid: ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  id: modules.my-sample-workload
  secretName: resource-secret-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  type: workload
  workloadPatchName: resource-patch-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
status: {}
