apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 1825edeca54f4778
    app.humanitec.io/env-type: development
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api-test
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: resource-032f852342482161c0016fda77e66860d81e7001
spec:
  configMapName: resource-configmap-032f852342482161c0016fda77e66860d81e7001
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies: []
      id: imagem-teste
      profile: humanitec/default-module
      spec:
        containers:
          flask-api-image-test:
            files: {}
            image: clecio/flask-api:latest
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
            variables: {}
            volume_mounts: {}
  driverType: humanitec/template
  guresid: 032f852342482161c0016fda77e66860d81e7001
  id: modules.imagem-teste
  secretName: resource-secret-032f852342482161c0016fda77e66860d81e7001
  type: workload
  workloadPatchName: resource-patch-032f852342482161c0016fda77e66860d81e7001
status: {}
