apiVersion: humanitec.io/v1alpha1
kind: Workload
metadata:
  annotations:
    app.humanitec.io/deployment: 1825edeca54f4778
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api-test
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: imagem-teste
spec:
  dependsOnResources:
  - resource-032f852342482161c0016fda77e66860d81e7001
  - resource-ecc1fbdaf305c0033c452e768415d363a9e149c1
  manifests:
  - apiVersion: v1
    data: {}
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: imagem-teste
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: imagem-teste
        helm.sh/chart: default-module-1.17.6
      name: imagem-teste-configmap-flask-api-image-test
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: imagem-teste
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: imagem-teste
        helm.sh/chart: default-module-1.17.6
      name: imagem-teste
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: imagem-teste
          app.kubernetes.io/name: imagem-teste
      template:
        metadata:
          annotations:
            checksum/config: e2145c65e4f088f2c3d6e5d156ad2b8cdad4fd69f0c73b62919a7825120187c6
          labels:
            app.kubernetes.io/instance: imagem-teste
            app.kubernetes.io/name: imagem-teste
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: imagem-teste-configmap-flask-api-image-test
            image: clecio/flask-api:latest
            name: flask-api-image-test
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
          imagePullSecrets: []
          serviceAccount: ""
          serviceAccountName: ""
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: imagem-teste
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: imagem-teste
        helm.sh/chart: default-module-1.17.6
      name: imagem-teste
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: imagem-teste
        app.kubernetes.io/name: imagem-teste
      type: ClusterIP
status: {}
