apiVersion: humanitec.io/v1alpha1
kind: Workload
metadata:
  annotations:
    app.humanitec.io/deployment: 1825edeca54f4778
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: flask-api-test
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: humaniteclab
  name: my-sample-workload
spec:
  dependsOnResources:
  - resource-ca3a091b98f089f5acbbecd1c0ead2e68bad7c79
  - resource-ecc1fbdaf305c0033c452e768415d363a9e149c1
  - resource-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
  - resource-e8bf0472ccecba849feeff1156acef99070e3b91
  manifests:
  - apiVersion: v1
    data: {}
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: my-sample-workload
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: my-sample-workload
        helm.sh/chart: default-module-1.17.6
      name: my-sample-workload-configmap-my-sample-container
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: my-sample-workload
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: my-sample-workload
        helm.sh/chart: default-module-1.17.6
      name: my-sample-workload
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: my-sample-workload
          app.kubernetes.io/name: my-sample-workload
      template:
        metadata:
          annotations:
            checksum/config: 8b94a42f66004c930c7b82f09720d8589324ac6b4b42cd5e2a3a76f2aeb7abd6
            humanitec.io/managed-by: Score
            humanitec.io/workload-artefact-name: my-sample-workload
          labels:
            app.kubernetes.io/instance: my-sample-workload
            app.kubernetes.io/name: my-sample-workload
        spec:
          containers:
          - env:
            - name: _MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: connection
                  name: resource-secret-e8bf0472ccecba849feeff1156acef99070e3b91
            - name: MONGODB_CONNECTION_STRING
              value: $(_MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_MONGODB_CONNECTION)
            - name: _MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: resource-configmap-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
            - name: _MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: resource-configmap-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
            - name: _MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: resource-secret-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
            - name: _MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: resource-secret-0fcae80115e2de3eb4ad7e928a4e6097e1ba8a91
            - name: REDIS_CONNECTION_STRING
              value: $(_MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_HOST):$(_MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_PORT),user=$(_MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_USERNAME),password=$(_MODULES.MY_SAMPLE_WORKLOAD.EXTERNALS.MY_REDIS_PASSWORD)
            envFrom:
            - configMapRef:
                name: my-sample-workload-configmap-my-sample-container
            image: nginx:latest
            name: my-sample-container
            resources:
              limits:
                cpu: 250m
                memory: 256Mi
              requests:
                cpu: 25m
                memory: 64Mi
          imagePullSecrets: []
          serviceAccount: ""
          serviceAccountName: ""
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: my-sample-workload
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: my-sample-workload
        helm.sh/chart: default-module-1.17.6
      name: my-sample-workload
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: my-sample-workload
        app.kubernetes.io/name: my-sample-workload
      type: ClusterIP
status: {}
